image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - dotnet restore src

build:
  - dotnet publish src

artifacts:
  - path: src\Cogito.Json\bin\**\*.nupkg
    name: Cogito.Json
  - path: src\Cogito.Json.Schema\bin\**\*.nupkg
    name: Cogito.Json.Schema
